name: Deployment pipeline

on:
  push:
    branches:
      - pipeline
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
  SECRET: ${{ secrets.SECRET }}
  PORT: ${{ secrets.PORT }}

jobs:
  simple_deployment_pipeline:
    name: Lint, Run Tests, and Deploy to Heroku
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-18.04
    steps:
      - name: CheckOut Repo
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: npm install backend
        run: npm install
      - name: npm install frontend
        run: cd client && npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
        env:
          NODE_ENV: "test"
      - name: e2e tests
        uses: cypress-io/github-action@v2
        env:
          NODE_ENV: "test"
        with:
          command: npm run test:e2e
          start: npm run start:test
          wait-on: http://localhost:5000
      - name: deploy to heroku
        if: "!contains(toJSON(github.event.commits.*.message), '#skip')"
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "secret-plains-85785"
          heroku_email: "nicholas.cruickshank25@gmail.com"
          healthcheck: "https://secret-plains-85785.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true

      - uses: actions/checkout@v2
      - name: Bump Version and Push Tag
        if: "github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip')"
        uses: anothrNick/github-tag-action@1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
